config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # Application Homepage
  get 'site/index'

  resources :clients
  resources :clienttypes
  resources :contacts
  resources :notes
  resources :keyvalues
  resources :users

  root 'site#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :clienttype
  has_many :contacts
  has_many :notes

  validates :name, presence: true
  validates :address, presence: true
  validates :zip, presence: true
  validates :city, presence: true
  validates :phone1, presence: true
  validates :email, presence: true
  
  # Setter and getter for clienttype text - useful for creation via dropdowns in forms
  def clienttype_text=(text)
    self.clienttype = Clienttype.find_by_text(text)
  end

  def clienttype_text
    self.clienttype ? self.clienttype.text : nil
  end

end

app/models/clienttype.rb
class Clienttype < ApplicationRecord
    has_many :clients

    validates :text, presence: true

end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :client
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :client
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :notes

    validates :firstname, presence: true
    validates :lastname, presence: true
    validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    def index
        @title = 'Client Index'
        @breadcrumbs = { "Clients"=>clients_path }
        @clients = Client.all.order(:name)
    end
    
    def show
        @title = 'View Client'
        @client = Client.find(params[:id])
    end

    def new
        @client = Client.new
    end

    def edit
        @client = Client.find(params[:id])
    end

    def create
        # This only works because I've made a clienttype_text
        # getter and setter in the client model, and use clienttype_text
        # In the form dropdown. (thus avoiding the use of ID in the UI)
        @client = Client.new(client_params)

        if @client.save
            redirect_to @client
        else
            render 'new'
        end
    end

    def update
        @client = Client.find(params[:id])
        
        if @client.update(client_params)
            redirect_to @client
        else
            render 'edit'
        end
    end

    def destroy
        @client = Client.find(params[:id])
        @client.destroy

        redirect_to clients_path
    end

    private

    def client_params
        params.require(:client).permit(:name,:cvr,:address,:zip,:city,:phone1,:phone2,:email,:website,:clienttype_text)
    end
end

app/controllers/clienttypes_controller.rb
class ClienttypesController < ApplicationController
    def index
        @title = 'Client Types Index'
        @breadcrumbs = { "Client Types"=>clienttypes_path }
        @clienttypes = Clienttype.all.order(:text)
    end
    
    def show
        @title = 'View Client Type'
        @clienttype = Clienttype.find(params[:id])
    end

    def new
        @clienttype = Clienttype.new
    end

    def edit
        @clienttype = Clienttype.find(params[:id])
    end

    def create
        @clienttype = Clienttype.new(clienttype_params)

        if @clienttype.save
            #redirect_to @clienttype
            redirect_to clienttypes_path
        else
            render 'new'
        end
    end

    def update
        @clienttype = Clienttype.find(params[:id])
        
        if @clienttype.update(clienttype_params)
            #redirect_to @clienttype
            redirect_to clienttypes_path
        else
            render 'edit'
        end
    end

    def destroy
        @clienttype = Clienttype.find(params[:id])
        @clienttype.destroy
        flash[:success] = 'The clienttype has been deleted'
        redirect_to clienttypes_path
    end

private
    def clienttype_params
        params.require(:clienttype).permit(:text)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    def index
        @title = 'Notes Index'
        @breadcrumbs = { "Notes"=>notes_path }
        @notes = Note.all
    end
    
    def show
        @title = 'View Note'
        @note = Note.find(params[:id])
    end

    def new
        @note = Note.new
    end

    def edit
        @note = Note.find(params[:id])
    end

    def create
        @note = Note.new(note_params)

        if @note.save
            redirect_to @note
        else
            render 'new'
        end
    end

    def update
        @note = Note.find(params[:id])
        
        if @note.update(note_params)
            redirect_to @note
        else
            render 'edit'
        end
    end

    def destroy
        @note = Note.find(params[:id])
        @note.destroy

        redirect_to notes_path
    end

private
    def note_params
        params.require(:note).permit(:text)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @title = 'Users Index'
        @breadcrumbs = { "Users"=>users_path }
        @users = User.all
    end
    
    def show
        @title = 'View User'
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def edit
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)

        if @user.save
            redirect_to users_path
        else
            render 'new'
        end
    end

    def update
        @user = User.find(params[:id])
        
        if @user.update(user_params)
            redirect_to users_path
        else
            render 'edit'
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy

        redirect_to users_path
    end

private
    def user_params
        params.require(:user).permit(:firstname, :lastname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clienttype_helper.rb
module ClienttypeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/clients/_card.html.erb
<div class="client-view">
    <div class="col-md-6">
        <b>Name and Address</b>
        <br>
        <%= @client.name %>
        <br>
        <%= @client.address; %>
        <br>
        <%= @client.zip + " " + @client.city %>
        <br>
        <br>
        <b>VAT Registration Number</b>
        <br>
        <%= @client.cvr %>
        <br>
    </div>


    <div class="col-md-6">
        <b>Client Number</b>
        <br>
        <%= @client.id %><br>
        <br>
        <b>Client Type</b>
        <br>
        <%= @client.clienttype_text %><br>
        <br>
        <b>Contact Info</b>
        <br>
        <i class="fa fa-phone fa-fw"></i><%= @client.phone1 %>
        <br>
        <% if !@client.phone2.blank? %>
            <i class='fa fa-phone fa-fw'></i><%= @client.phone2 %><br>
        <% end %>
        <i class="fa fa-envelope fa-fw"></i> <a href="mailto:<%= @client.email %>"><%= @client.email %></a>
        <br>
        <% if !@client.website.blank? %>
            <i class="fa fa-globe fa-fw"></i><a href="<%= @client.website %>"><%= @client.website %></a><br>
        <% end %>
        <br>
    </div>

</div>

app/views/clients/edit.html.erb
<h1>Edit Client</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Clients</h3>
    <div class="input-group input-group-sm" style="width: 150px;">
      <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
      <div class="input-group-btn">
        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
      </div>
    </div>
  </div> <!-- /.box-header -->

  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Address</th>
          <th>Zip</th>
          <th>City</th>
          <th>Phone1</th>
          <!--<th>Phone2</th>-->
          <th>Email</th>
          <!--<th>Website</th>-->
          <!--<th>Clienttype</th>-->
          <th></th>
        </tr>
      </thead>
    
      <tbody>
        <% @clients.each do |client| %>
          <tr  data-link="<%= client_path(client) %>">
            <td><%= client.id %></td>
            <td><%= client.name %></td>
            <td><%= client.address %></td>
            <td><%= client.zip %></td>
            <td><%= client.city %></td>
            <td><%= client.phone1 %></td>
            <!--<td><%= client.phone2 %></td>-->
            <td><a href="mailto:<%= client.email %>"><%= client.email %></a></td>
            <!--<td><%= client.website %></td>-->
            <!--<td><%= client.clienttype.text %></td>-->
            <td style='text-align:right;' data-nolink>
              <%= link_to '<i class="fa fa-eye"></i>'.html_safe, client %>&nbsp;
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_client_path(client) %>&nbsp;
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe,
                client, 
                method: :delete, 
                data: {confirm_swal: "Are you sure?"} 
              %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- /.box-body -->

</div> <!-- /.box -->
 
<%= link_to "Add New Client", new_client_path %>

<script>
//$("tr[data-link]").click(function() {
//    if $this.find("td")
//    window.location = $(this).data("link")
//})
</script>

app/views/clients/new.html.erb
<h1>New Client</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', clients_path %>

app/views/clienttypes/index.html.erb
<% flash.each do |type, message| %>
      <div><%= message %></div>
<% end %>

<div class="box">
  <div class="box-header">
    <h3 class="box-title">Client Types</h3>
    <div class="input-group input-group-sm" style="width: 150px;">
      <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
      <div class="input-group-btn">
        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
      </div>
    </div>
  </div> <!-- /.box-header -->

  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>Text</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @clienttypes.each do |clienttype| %>
          <tr>
            <td><%= clienttype.id %></td>
            <td><%= clienttype.text %></td>
            <td style='text-align:right;'>
              <%= link_to '<i class="fa fa-eye"></i>'.html_safe, clienttype %>&nbsp;
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_clienttype_path(clienttype) %>&nbsp;
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe,
                clienttype,
                method: :delete,
                data: {confirm_swal: 'Are you sure?'}
              %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- /.box-body -->

</div> <!-- /.box -->
 
<%= link_to "Add New Client Type", new_clienttype_path %>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Contacts</h3>
    <div class="input-group input-group-sm" style="width: 150px;">
      <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
      <div class="input-group-btn">
        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
      </div>
    </div>
  </div> <!-- /.box-header -->

  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>Client</th>
          <th>User</th>
          <th>Text</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @contacts.each do |contact| %>
          <tr>
            <td><%= contact.id %></td>
            <td><%= contact.client.name %></td>
            <td><%= contact.user.firstname contact.user.lastname %></td>
            <td><%= contact.text %></td>
            <td style='text-align:right;'>
              <%= link_to '<i class="fa fa-eye"></i>'.html_safe, contact %>&nbsp;
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_contact_path(contact) %>&nbsp;
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, contact, method: :delete, data: { confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- /.box-body -->

</div> <!-- /.box -->
 
<%= link_to "Add New Contact", new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClientDB</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="skin-blue sidebar-mini">

  <div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="<%= site_index_path %>" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>C</b>DB</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Client</b>DB</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>
                <!-- inner menu: contains the messages -->
                <ul class="menu">
                  <li><!-- start message -->
                    <a href="#">
                      <div class="pull-left">
                        <!-- User Image -->
                        <img src="/images/user2-160x160.jpg" class="img-circle" alt="User Image">
                      </div>
                      <!-- Message title and timestamp -->
                      <h4>
                        Reception
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>
                      <!-- The message -->
                      <p>Please call back a new possible client!</p>
                    </a>
                  </li>
                  <!-- end message -->
                </ul>
                <!-- /.menu -->
              </li>
              <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
          </li>
          <!-- /.messages-menu -->

          <!-- Notifications Menu -->
          <li class="dropdown notifications-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning">10</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 10 notifications</li>
              <li>
                <!-- Inner Menu: contains the notifications -->
                <ul class="menu">
                  <li><!-- start notification -->
                    <a href="#">
                      <i class="fa fa-users text-aqua"></i> Remember to send invoice to Client X</a>
                  </li>
                  <!-- end notification -->
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li>
            </ul>
          </li>
          <!-- Tasks Menu -->
          <li class="dropdown tasks-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-flag-o"></i>
              <span class="label label-danger">9</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 9 tasks</li>
              <li>
                <!-- Inner menu: contains the tasks -->
                <ul class="menu">
                  <li><!-- Task item -->
                    <a href="#">
                      <!-- Task title and progress text -->
                      <h3>
                        Add more features to the Client DB app.
                        <small class="pull-right">20%</small>
                      </h3>
                      <!-- The progress bar -->
                      <div class="progress xs">
                        <!-- Change the css width attribute to simulate progress -->
                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">20% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                </ul>
              </li>
              <li class="footer">
                <a href="#">View all tasks</a>
              </li>
            </ul>
          </li>
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <img src="/images/user2-160x160.jpg" class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">Carsten Skjerk</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="/images/user2-160x160.jpg" class="img-circle" alt="User Image">

                <p>
                  Carsten Skjerk - Senior Developer
                  <small>Creator of this Rails app</small>
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/images/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Carsten Skjerk</p>
          <!-- Status -->
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <!-- search form (Optional) -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
        </div>
      </form>
      <!-- /.search form -->

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Main menu</li>
        <!-- Optionally, you can add icons to the links -->
        <li class="active"><a href="<%= clients_path %>"><i class="fa fa-users"></i> <span>Clients</span></a></li>
        <li><a href="<%= clienttypes_path %>"><i class="fa fa-address-card-o"></i> <span>Client Types</span></a></li>
        <li><a href="<%= users_path %>"><i class="fa fa-user"></i> <span>Users</span></a></li>
<!--        <li class="treeview">
          <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="#">Link in level 2</a></li>
            <li><a href="#">Link in level 2</a></li>
          </ul>
        </li> -->
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1><%= @title %></h1>
      <ol class="breadcrumb">
        <li><a href="<%= site_index_path %>"><i class="fa fa-dashboard"></i> Site index</a></li>
        <% if @breadcrumbs %>
          <% @breadcrumbs.each do |b| %>
              <li class="active"><a href="<%= b[1] %>"><%= b[0] %></a></li>
          <% end %>
        <% end %>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">

      <!--------------------------
        | Your Page Content Here |
        -------------------------->
            <%= yield %>


    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Make a client happy today!
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2018 <a href="#">Carsten Skjerk</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="pull-right-container">
                    <span class="label label-danger pull-right">70%</span>
                  </span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
  immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->
<script> $('body').layout('fix'); </script>
</body>
</html>

app/views/notes/index.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Notes</h3>
    <div class="input-group input-group-sm" style="width: 150px;">
      <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
      <div class="input-group-btn">
        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
      </div>
    </div>
  </div> <!-- /.box-header -->

  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>Client</th>
          <th>User</th>
          <th>Text</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @notes.each do |note| %>
          <tr>
            <td><%= note.id %></td>
            <td><%= note.client.name %></td>
            <td><%= note.user.firstname note.user.lastname %></td>
            <td><%= note.text %></td>
            <td style='text-align:right;'>
              <%= link_to '<i class="fa fa-eye"></i>'.html_safe, note %>&nbsp;
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_note_path(note) %>&nbsp;
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, note, method: :delete, data: { confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- /.box-body -->

</div> <!-- /.box -->
 
<%= link_to "Add New Note", new_note_path %>

app/views/users/index.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Users</h3>
    <div class="input-group input-group-sm" style="width: 150px;">
      <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
      <div class="input-group-btn">
        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
      </div>
    </div>
  </div> <!-- /.box-header -->

  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.firstname %> <%= user.lastname %></td>
            <td><%= user.email %></td>
            <td style='text-align:right;'>
              <%= link_to '<i class="fa fa-eye"></i>'.html_safe, user %>&nbsp;
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_user_path(user) %>&nbsp;
             <%= link_to '<i class="fa fa-trash"></i>'.html_safe,
                user, 
                method: :delete, 
                data: {confirm_swal: "Are you sure you want to delete this user?"} 
              %>
           
          </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- /.box-body -->

</div> <!-- /.box -->
 
<%= link_to "Add New User", new_user_path %>